### ISSUE TITLE
Valid period for invoices 1 day too long

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#208]
The validity period for for the invoices should be 7 days. As invoice creation job is run at the beginning of a day the issue date is also counted in as a full day. Because of that traditional calculation issue_date + 7 results in a payment period of full 8 days.

To fix the calculation  one option would be to add a setting for payment term - last day included/excluded. Meaning that if period of 7 is specified, does the calculated due date mean that user has to pay the invoice before that date or at that date the latest. On the invoice we always show date as inclusive. That means if  setup is last day excluded the due date on invoice needs to be -1 from actual calculated due date.

Other approaches to solve this issue are possible.

**Comment by maciej-szlosarczyk** [comment]
I do not think the introduction of additional variable to the code is beneficial since we can get the same functionality by using `payment_term` Setting with value 6. A new variable would double the scenarios we need to cover while testing.

Alternative approach: we can make the Setting text a bit better to make it more obvious that it is current date + number of full days. Currently the text reads:
```
Number of days before which an invoice for auction must be paid. Default: 7
```

Proposed change:
```
Number of full days before which an invoice for auction must be paid. When an invoice is created on 1st day of the month, its due date is the 8th day of the same month. Default: 7
```

**Comment by vohmar** [comment]
Agreed, I indeed did overengineer this thing in my head.

Setting text proposal:
Number of full days after the issue date the recipient has time to pay for the invoice. If invoices are generated at the start of a day you might want to substract 1 from the setting to achieve desired invoice due date.
