### ISSUE TITLE
Alert for paid but not registered domains

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#264]
There is quite many auctions that have been paid for but were not successfully registered after that.  The goal is to reduce this number to 0 and to do that we need to know in advance when some of such domains is getting too close to registration deadline.

* Add an option to enable such alert,
* configuration option when to raise the alert (ie 1 or 2 days in advance)
* different options for alerting - report in auction admin for paid but unregistered domains with day count to deadline and stressing the critical ones, email alert to list of email addresses)

**Comment by maciej-szlosarczyk** [comment]
After thinking about for a while, it's a bit shallow. I think we can expand this a little bit into a daily summary email functionality to get statistics into it too because we have a bit of visibility problem. Should tie in with #174 a bit. 

An administrator can choose to receive emails every morning about:
- What domains were auctioned yesterday, ordered by the final price.
- How many domains are due to be released with no bids (just a number, not a list).
- Domains that have a registration deadline tomorrow with contact data to the customer.
- If there were any unpaid invoices/bans.

Similarly, we can create a weekly digest of what happened in auction on a slightly higher level, without personal information that can be sent to executives, not auction administrators. Something that contains the following information:
- There were total 200 auctions during the week of 29.04.2019 - 05.03.2019.
- In total, customers made 100 offers. The most popular was auction.com that received 30 offers.
- 152 domains had no bids and were released.
- Highest bid was 100 $ for foobar.com, and the total projected revenue from issued invoices is 400 $.
- There were 3 unpaid invoices, resulting in bans for 2 customers.

**Comment by vohmar** [comment]
daily report is in place
