### ISSUE TITLE
Unexpected sorting behavior at `/admin/auctions`

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/auction_center#321]
Only the first sorting column is taken into account since the page load.

Example:
Navigate to `/admin/auctions?order%5Badmin_auction_decorators.domain_name%5D=asc` and try to sort by any other column than domain name. Notice that auctions are only sorted by domain name, with no regard to other columns, specified in URL (`/admin/auctions?order%5Badmin_auction_decorators.domain_name%5D=asc&order%5Badmin_auction_decorators.ends_at%5D=asc&order%5Badmin_auction_decorators.starts_at%5D=asc`).

I am not sure what is the expected behavior here, but it's definitely not good when I click on multiple columns and don't get expected results nor any feedback about improper use of UI.

**Comment by yulgolem** [comment]
I suppose works as expected.

I've added a fixture with same domain name to check.
Unsorted list looks like:
![image](https://user-images.githubusercontent.com/7688888/67462681-7d868180-f659-11e9-8193-75a9c3ed2a1c.png)

Then sorted by domains name desc:
![image](https://user-images.githubusercontent.com/7688888/67462775-9ee76d80-f659-11e9-9d93-444ba76600f4.png)
Note the dates of start/end and # of offers on two last auctions with same domain.
The order part of SQL-query now is `ORDER BY auctions.domain_name asc NULLS LAST `.

Now let's sort by # of offers asc:
![image](https://user-images.githubusercontent.com/7688888/67464054-10c0b680-f65c-11e9-9e73-dac4a8f6bae6.png)
Again note the dates of start/end and # of offres on two last auctions with same domain.
And the order part of query is ` ORDER BY auctions.domain_name asc NULLS LAST, auctions.number_of_offers desc NULLS LAST`.

So - the next level of sorting is on only when there is a some equal entities of the previous level - ie domain name in our case. If we'll try to sort this dataset bu some other field - the sorting will fails since its already sorted.

That was locally, I'll try and see how it's going on staging.

**Comment by vohmar** [comment]
closing this issue with partial solution by PR #383. Work is continued in issue #400 which has more details on the topic
