### ISSUE TITLE
Auto-run data migrations on deploy

### ISSUE THREAD

**Issue by yulgolem** [internetee/auction_center#513]
We need some way to automatically run all previous/actual data migrations as per usual DB migrations.

Possible variants:
1) move data migrations to db migrations, on separate classes.
2) make a rake-task which automatically run all data migrations in order of timestamps (need to change name structure) and add this task to deploy script.

@vohmar , @karlerikounapuu Any ideas?

**Comment by karlerikounapuu** [comment]
In order to run data migrations automatically, we should somehow implement some simple versioning for data migrations as well as current out-of-box solution for regular migrations. I believe our current data migrations are not reversible nor designed for rerunning multiple times. They're meant for "run once" behaviour.

I would go with solution no 2. We could also create post-hook for db:migrate task via `enhance` so it runs that custom rake task in addition to db:migrate without custom deploy script tuning.

**Comment by yulgolem** [comment]
Let's consider this gem for versioning/migrating - https://github.com/ilyakatz/data-migrate

**Comment by teadur** [comment]
I proposed we use data-migrate in registry aswell so going with same solution for both makes sense :)

https://github.com/internetee/registry/issues/1298

**Comment by yulgolem** [comment]
Need to add `bundle exec rake data:migrate` to deploy scripts to run data migrations.
Already added it to travis.yml.

**Comment by vohmar** [comment]
the #525 is merged to master and to close this issue the deploy scripts need to be updated. @teadur @ratM1n please do so.

**Comment by vohmar** [comment]
fixed by #525
